name: "Verify type labels"

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

permissions:
  contents: none

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: baev/match-label-action@master
        with:
          allowed: 'type:bug,type:new feature,type:improvement,type:dependencies,type:internal,type:invalid'
